import { Resvg } from "@resvg/resvg-js";
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

function badgeSvg(label) {
  // Font sizing tuned for readability at 16-32 px taskbar overlay.
  const fontSize = label.length === 1 ? 20 : label.length === 2 ? 15 : 12;
  const yOffset = label.length === 1 ? 23 : label.length === 2 ? 22 : 21;
  return `<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
    <circle cx="16" cy="16" r="15" fill="#E5484D"/>
    <circle cx="16" cy="16" r="15" fill="none" stroke="white" stroke-width="1.25"/>
    <text x="16" y="${yOffset}" text-anchor="middle"
          font-family="Segoe UI, Arial Black, sans-serif"
          font-size="${fontSize}" font-weight="900" fill="white">${label}</text>
  </svg>`;
}

// Labels: "1" through "99", plus "99+" for counts >= 100.
const labels = [];
for (let i = 1; i <= 99; i++) labels.push(String(i));
labels.push("99+");

const outDir = resolve(root, "src-tauri/icons/badges");
mkdirSync(outDir, { recursive: true });
for (const label of labels) {
  const resvg = new Resvg(badgeSvg(label), { background: "rgba(0,0,0,0)" });
  const png = resvg.render().asPng();
  const name = label === "99+" ? "badge-99plus.png" : `badge-${label}.png`;
  writeFileSync(resolve(outDir, name), png);
}
console.log(`wrote ${labels.length} PNG badges to ${outDir}`);

// Also emit a Rust file with the byte arrays so badge.rs doesn't need 100
// hand-written include_bytes! lines. Regenerate whenever labels change.
const rsPath = resolve(root, "src-tauri/src/badge_data.rs");
const entries = labels.map((label) => {
  const name = label === "99+" ? "badge-99plus.png" : `badge-${label}.png`;
  return `    include_bytes!(\"../icons/badges/${name}\"),`;
});
const rs = `// Auto-generated by scripts/gen-badges.mjs. Do not edit by hand.
// Indexes 0..=98 correspond to counts 1..=99; index 99 is the \"99+\" badge
// used for any count >= 100.

#[cfg(windows)]
pub const BADGES: [&[u8]; ${labels.length}] = [
${entries.join("\n")}
];
`;
writeFileSync(rsPath, rs);
console.log(`wrote ${rsPath}`);
